#!/bin/bash

alias realias="source $HOME/.bash_aliases"
#alias edaemon="emacs --daemon"
alias enw="emacsclient"
alias enw="emacs -nw"

alias tomcat="$CATALINA_HOME/bin/catalina.sh jpda"
alias logs="tail -f $CATALINA_HOME/work/logs/*.log $CATALINA_HOME/logs/*.log"
alias tomcat?="ps -ef | grep  tomcat"
alias clog="rm -rf /opt/tomcat/logs/*.log.* /opt/tomcat/logs/*.*.log /opt/tomcat/work/logs/*.log.* /opt/tomcat/logs/*.*.log"

alias pgstart="sudo /etc/init.d/postgresql start"
alias pgstop="sudo /etc/init.d/postgresql stop"

alias tgrep="grep --color -n -R"
alias nfind="find ./ -name"

alias mci="mvn clean install"
alias mii="mvn -Pinit-db"
alias mpp="mvn -Ppopulate"
alias mpu="mvn -Ppopulate-useradmin"
alias mtc="mvn tomcat:redeploy"
alias mip="mvn -Pinit-db; mvn -Ppopulate"
alias mit="mvn -Pinit-db; mvn tomcat:redeploy"
alias mipt="mvn -Pinit-db; mvn -Ppopulate; mvn tomcat:redeploy"
alias psg="ps aux | grep"
alias mcs="mvn verify -DskipTests -Pcheckstyle"
alias mcist="mci -DskipTests"
alias ccache="sudo sync && sudo echo 3 | sudo tee /proc/sys/vm/drop_caches"

alias gpd="git push origin HEAD:refs/drafts/master"
alias gpf="git push origin HEAD:refs/for/master"
alias gpr="git pull --rebase"

alias grh="git reset HEAD ."
alias gco="git checkout -- ."
alias stashpp="git stash; git pull --rebase; git stash pop"
alias cdnmo="cd /other/dev/client-NewMexicoOrtho"
alias cdcp="cd /other/dev/perception/card_recognition/card_processing"
alias cdocr="cd /other/dev/insurance-card-ocr"
alias cdvg="cd /other/dev/vecna-global"
alias buper="cd /other/dev/kiosk-platform/peripherals/;mvn clean install; cd /other/dev/vps/peripherals/;mvn clean install"
alias cdt="cd /other/dev/test"
alias cdw="cd ~/workspace"
alias cdo="cd /other"
alias veclipse="/other/eclipse/eclipse"
alias cdvm="cd ~/workspace/vermoi-code"
alias tobyrd="ssh root@vanationalload.crl.vecna.com"

alias remove_trailing_space="find ./ -name '*.xml' | xargs sed -i -e 's\ \{1,\}$//'"
alias cdc2c="cd /other/dev/kiosk-clients/client-Clinipak-C2C"
alias ecnw="emacsclient -nw"
alias cdics="cd /other/dev/kiosk/platform/insurance-card-scanning"
alias nab="/other/dev/kiosk/util/build/autobuild/autobuild.py"
alias rsync_music="rsync -avz --delete /home/sun/Music/ /media/sun/COWON/MUSIC/"
alias cdebola="cd /other/dev/kiosk-clients/client-Clinipak-Ebola"
alias startjetty="mvn db-manager:create build-helper:reserve-network-port -DminPort=9000 -DmaxPort=9001 jetty:run -DskipITs=false -Djetty.port=9000"

alias cden="cd ~/Den"
